name: deploy

on:
  push:
    branches:
      - main

jobs:
  audit:
    uses: './.github/workflows/audit.yaml'

  deploy:
    name: Deploy to Production
    needs: [audit]
    runs-on: ubuntu-latest

    steps:
      - name: execute ssh command
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}

          script: |

            deploy_project () {

              echo "==============================="
              echo "🚀 Deploying $1"
              echo "==============================="

              cd ~/$1

              # Sauvegarder les fichiers/dossiers à préserver
              cp -r config /tmp/config_backup || true
              cp -r storage /tmp/storage_backup || true
              cp -r public /tmp/public_backup || true

              echo '--- AVANT PULL ---'
              git status
              ls -l

              git reset --hard
              git clean -fd
              git pull origin main --rebase

              echo '--- APRES PULL ---'
              git status
              ls -l

              # Supprimer rapids si présent
              if grep -q 'rapids/rapids' composer.json; then
                composer remove rapids/rapids || true
              fi

              # Restaurer les fichiers sauvegardés
              rsync -a /tmp/config_backup/ config/ || true
              rsync -a /tmp/storage_backup/ storage/ || true
              rsync -a /tmp/public_backup/ public/ || true

              rm -rf /tmp/config_backup /tmp/storage_backup /tmp/public_backup

              # Installer dépendances production
              composer install --no-dev --optimize-autoloader

              # Laravel
              php artisan migrate --force

              php artisan config:cache
              php artisan route:cache

              php artisan view:clear
              php artisan view:cache

              php artisan cache:clear
              php artisan config:clear
              php artisan route:clear
              php artisan view:clear

              echo "✅ Deployment finished for $1"

            }

            deploy_project "enabel.inafrica.tech"
            deploy_project "pgfe-back.inafrica.tech"

      - name: Notify Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="🚀 Deployment SUCCESS

          Repo: ${{ github.repository }}
          Branch: ${{ github.ref_name }}
          Commit: ${{ github.sha }}

          Domains deployed:
          ✅ enabel.inafrica.tech
          ✅ pgfe-back.inafrica.tech

          Time: $(date)"
